import os
import json



class GodotWorker:


    def __init__(
        self,
        provider_manager
    ):

        self.provider = provider_manager



    def run(
        self,
        job,
        package_path
    ):


        asset_name = self.create_asset_name(
            job.request
        )


        godot_path = os.path.join(

            package_path,

            "godot"

        )


        self.create_folders(
            godot_path
        )


        self.create_scene(

            godot_path,

            asset_name

        )


        self.create_script(

            godot_path,

            asset_name

        )


        self.create_spriteframes(

            godot_path,

            asset_name

        )


        self.create_metadata(

            godot_path,

            asset_name

        )


        return godot_path



    def create_folders(
        self,
        path
    ):


        folders = [

            "scenes",

            "scripts",

            "resources",

            "spriteframes",

            "project_config"

        ]


        for folder in folders:


            os.makedirs(

                os.path.join(

                    path,

                    folder

                ),

                exist_ok=True

            )



    def create_asset_name(
        self,
        request
    ):


        words = request.lower().split()


        return "_".join(

            words[:3]

        )



    def create_scene(
        self,
        path,
        asset_name
    ):


        content = f"""[gd_scene load_steps=2 format=3]


[node name="{asset_name}" type="CharacterBody2D"]


[node name="AnimatedSprite2D" type="AnimatedSprite2D" parent="."]


"""


        file_path = os.path.join(

            path,

            "scenes",

            asset_name + ".tscn"

        )


        self.write_file(

            file_path,

            content

        )



    def create_script(
        self,
        path,
        asset_name
    ):


        content = f"""extends CharacterBody2D


# Generated by Project Forge


func _ready():

    print("{asset_name} initialized")



func _physics_process(delta):

    pass

"""


        file_path = os.path.join(

            path,

            "scripts",

            asset_name + ".gd"

        )


        self.write_file(

            file_path,

            content

        )



    def create_spriteframes(
        self,
        path,
        asset_name
    ):


        content = f"""[gd_resource type="SpriteFrames" format=3]


[resource]

resource_name = "{asset_name}_animations"

"""


        file_path = os.path.join(

            path,

            "spriteframes",

            asset_name + ".spriteframes"

        )


        self.write_file(

            file_path,

            content

        )



    def create_metadata(
        self,
        path,
        asset_name
    ):


        data = {


            "asset": asset_name,


            "engine": "Godot 4",

            "type": "character_package",


            "scene": True,


            "script": True,


            "spriteframes": True,


            "status": "prepared"


        }



        file_path = os.path.join(

            path,

            "project_config",

            "godot_metadata.json"

        )


        with open(

            file_path,

            "w",

            encoding="utf-8"

        ) as file:


            json.dump(

                data,

                file,

                indent=4,

                ensure_ascii=False

            )



    def write_file(
        self,
        path,
        content
    ):


        with open(

            path,

            "w",

            encoding="utf-8"

        ) as file:


            file.write(

                content

            )